=== wzuyderwyk/CV/PHP/DTDs/coursexml.dtd
<!--
	### courseXml ###	-->

<!-- Entities worden hier geÃ¯nitialiseerd -->
<!ENTITY % DaysDesc "(event)+">

<!-- Elementen worden hier beschreven -->
<!ELEMENT course (timetable, reqs)>
<!ELEMENT timetable (monday, tuesday, wednesday, thursday, friday)>

<!ELEMENT monday %DaysDesc;>
<!ELEMENT tuesday %DaysDesc;>
<!ELEMENT wednesday %DaysDesc;>
<!ELEMENT thursday %DaysDesc;>
<!ELEMENT friday %DaysDesc;>

<!ELEMENT event (description, location)?>
<!ELEMENT description (#PCDATA)>
<!ELEMENT location (#PCDATA)>

<!ELEMENT reqs (req)+>
<!ELEMENT req (description, details)>
<!ELEMENT details (#PCDATA)>

<!-- Attributen worden hier beschreven -->
<!ATTLIST event
	type	(lecture|workshop|free)	#REQUIRED
	>

=== wzuyderwyk/CV/PHP/courses/cs001.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE course SYSTEM "http://webdev.ru.nl/DTDs/coursexml.dtd">
<course>
	<timetable>
		<monday>
			<event type="free"/>
			<event type="lecture">
				<description>Een hoorcollege</description>
				<location>CC02</location>
			</event>
			<event type="workshop">
				<description>Een werkcollege</description>
				<location>E. 2.10</location>
			</event>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
		</monday>
		<tuesday>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
		</tuesday>
		<wednesday>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
		</wednesday>
		<thursday>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
		</thursday>
		<friday>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
			<event type="free"/>
		</friday>
	</timetable>

	<reqs>
		<req>
			<description>Voor deze cursus moet je alles weten over Web Development</description>
			<details>Dus: sluit de toets af met een voldoende</details>
		</req>
		<req>
			<description>Voor deze cursus moet je alles weten over Web Design</description>
			<details>Dus maak een adequate persona</details>
		</req>
	</reqs>
</course>
